version: "2.1"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  scheduler:
    image: nhatthai/airflow-python3.7:celery
    restart: always
    depends_on:
      - postgres
      - webserver
      - redis
    env_file:
      - .env
    ports:
      - "8793:8793"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  webserver:
    image: nhatthai/airflow-python3.7:celery
    hostname: webserver
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    entrypoint: ./scripts/airflow-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: nhatthai/airflow-python3.7:celery
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - EXECUTOR=Celery
    ports:
      - "5555:5555"
    command: flower

  worker:
    image: nhatthai/airflow-python3.7:celery
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
    env_file:
      - .env
    command: worker -q queue1